### DISCUSSION TITLE
What's in `application.yml`

### DISCUSSION THREAD

**Discussion by gil-log** [gil-log/ddd-practice#9] [General]
[22.11.23]
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: gillog
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

**Comment by gil-log** [comment]
[22.11.24]
```
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=1
  jpa:
    show-sql: true
```
